const adjectives = [
  "Humorous",
  "Silly",
  "Witty",
  "Clever",
  "Playful",
  "Quirky",
  "Bouncy",
  "Zesty",
  "Fuzzy",
  "Wobbly",
  "Giggly",
  "Bubbly",
  "Snazzy",
  "Dizzy",
  "Wacky",
  "Goofy",
  "Fluffy",
  "Bouncy",
  "Squishy",
  "Wiggly",
  "Jumpy",
  "Bumpy",
  "Wobbly",
  "Squeaky",
  "Puffy",
  "Floppy",
  "Wiggly",
  "Bouncy",
  "Squishy",
  "Wobbly",
  "Jumpy",
  "Bumpy",
];

const animals = [
  "Hippopotamus",
  "Penguin",
  "Platypus",
  "Narwhal",
  "Quokka",
  "Axolotl",
  "Capybara",
  "Sloth",
  "Pangolin",
  "Okapi",
  "Tarsier",
  "Fossa",
  "Aye-aye",
  "Shoebill",
  "Blobfish",
  "Dugong",
  "Manatee",
  "Wombat",
  "Kinkajou",
  "Fennec",
  "Tardigrade",
  "Numbat",
  "Quoll",
  "Binturong",
  "Sunda Colugo",
  "Pink Fairy Armadillo",
  "Dumbo Octopus",
];

export function generateSessionTitle(): string {
  const randomAdjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomAnimal = animals[Math.floor(Math.random() * animals.length)];
  return `${randomAdjective} ${randomAnimal}`;
}
