// pages/terms.tsx
import Head from "next/head";

export default function TermsOfService() {
  return (
    <>
      <section className="min-h-[calc(100dvh-4rem)] md:min-h[calc(100dvh-5rem)] z-10 flex flex-col items-center justify-center bg-blue-50/30 ">
        <main className="mt-8 max-w-[390px] lg:max-w-6xl  w-full mx-auto container">
          <Head>
            <title>Terms of Service | Sanv AI</title>
            <meta name="description" content="Terms of Service for Sanv AI" />
          </Head>
          <main className="px-4 py-8 md:px-8">
            <div className="prose prose-blue max-w-prose mx-auto prose-pre:m-0 prose-pre:bg-transparent prose-pre:p-0">
              <h1>Sanv AI Terms of Service</h1>
              <p>
                <strong>Last Updated:</strong> 2025-01-08
              </p>

              <h2>1. Introduction</h2>
              <p>
                Welcome to <strong>Sanv AI</strong> (“<strong>Service</strong>
                ”), a platform designed to provide AI-powered speech and
                behavioral insights. Sanv AI is developed and operated by{" "}
                <strong>Neurotechh</strong> (“<strong>we</strong>,” “
                <strong>us</strong>,” or “<strong>our</strong>”). By accessing
                or using Sanv AI, you agree to comply with and be bound by these
                Terms of Service (“<strong>Terms</strong>”).
              </p>
              <p>
                If you do not agree with any part of these Terms, you must not
                use Sanv AI.
              </p>

              <h2>2. Eligibility</h2>
              <p>You may use Sanv AI only if:</p>
              <ol>
                <li>
                  You are at least the age of majority in your jurisdiction;
                </li>
                <li>You have the legal authority to enter into these Terms.</li>
              </ol>

              <h2>3. Acceptance of Terms</h2>
              <p>
                By accessing or using Sanv AI, you confirm that you have read,
                understood, and agree to be bound by these Terms and applicable
                laws.
              </p>

              <h2>4. Modifications</h2>
              <p>
                We reserve the right to modify these Terms at any time. Changes
                will be posted on our website and reflected by the “Last
                Updated” date. Continued use of the Service means you accept the
                changes.
              </p>

              <h2>5. Description of the Service</h2>
              <p>
                <strong>5.1. Functionality</strong>
                <br />
                Sanv AI provides real-time or text-based feedback on speech and
                behavioral attributes using AI models. It is not a substitute
                for clinical or professional advice.
              </p>
              <p>
                <strong>5.2. AI Outputs</strong>
                <br />
                Outputs are generated by large language and speech models and
                may not always be accurate or complete.
              </p>
              <p>
                <strong>5.3. Updates</strong>
                <br />
                We may change or discontinue any aspect of the Service without
                notice.
              </p>

              <h2>6. User Conduct</h2>
              <p>By using the Service, you agree not to:</p>
              <ol>
                <li>Violate any laws or these Terms.</li>
                <li>Use it for harmful or abusive purposes.</li>
                <li>Disrupt or interfere with its operation.</li>
                <li>Upload malicious code.</li>
                <li>Harvest data from other users.</li>
                <li>Infringe intellectual property rights.</li>
              </ol>

              <h2>7. Privacy</h2>
              <p>
                Your use of Sanv AI is subject to our{" "}
                <strong>Privacy Policy</strong>, which outlines how we collect
                and use your data.
              </p>

              <h2>8. Intellectual Property</h2>
              <ol>
                <li>
                  <strong>Ownership:</strong> We retain all rights to the
                  Service and its content.
                </li>
                <li>
                  <strong>User Content License:</strong> You grant us a license
                  to use content you submit to Sanv AI to improve the Service.
                </li>
                <li>
                  <strong>Trademarks:</strong> Sanv AI branding is protected.
                </li>
              </ol>

              <h2>9. Disclaimers</h2>
              <ol>
                <li>
                  <strong>No Warranty:</strong> Service is provided “as is.”
                </li>
                <li>
                  <strong>Information Accuracy:</strong> We don’t guarantee
                  output accuracy.
                </li>
                <li>
                  <strong>Professional Advice:</strong> This is not a
                  replacement for expert consultation.
                </li>
              </ol>

              <h2>10. Limitation of Liability</h2>
              <ol>
                <li>We’re not liable for indirect damages.</li>
                <li>
                  Maximum liability is $100 or the amount you paid in the past
                  12 months, whichever is greater.
                </li>
              </ol>

              <h2>11. Indemnification</h2>
              <p>
                You agree to indemnify us against claims arising from your use
                of the Service or your violation of these Terms.
              </p>

              <h2>12. Third-Party Services</h2>
              <p>
                Sanv AI may link to or use third-party services. We’re not
                responsible for their content or actions.
              </p>

              <h2>13. Term and Termination</h2>
              <ol>
                <li>These Terms remain in effect while you use Sanv AI.</li>
                <li>You may stop using the Service at any time.</li>
                <li>
                  We may terminate your access if you violate these Terms.
                </li>
              </ol>

              <h2>14. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the jurisdiction where
                Neurotechh is registered. Disputes will be handled in those
                courts.
              </p>

              <h2>15. Changes to the Service</h2>
              <p>We may change, suspend, or end the Service at any time.</p>

              <h2>16. General</h2>
              <ol>
                <li>
                  <strong>Severability:</strong> If any part is invalid, the
                  rest remains effective.
                </li>
                <li>
                  <strong>No Waiver:</strong> Not enforcing a term doesn’t waive
                  our right to do so later.
                </li>
                <li>
                  <strong>Entire Agreement:</strong> These Terms are the entire
                  agreement between us and you.
                </li>
                <li>
                  <strong>Assignment:</strong> You may not transfer your rights
                  without our consent.
                </li>
              </ol>
            </div>
          </main>
        </main>
      </section>
    </>
  );
}
